---
title: "fft2"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{fft2}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message = FALSE}
library(microclimr)
library(dplyr)
library(ggplot2)
```

```{r data}
t <- 10
n <- 201
data <- tibble(
  time = (seq_len(n) - 1) * t / n
) %>%
  mutate(
    temperature = 14 +
      0.5 * cos(2 * pi * (time - 0.5) * 2 / t) +
      3 * cos(2 * pi * (time - 0.1) * 4 / t) + 0.3 * rnorm(n)
  )
(g <- ggplot(data, aes(time, temperature)) +
  geom_point() + #nolint
  theme_bw())
```

```{r decomposition}
fc <- fft_rfft(data$temperature)
freq <- fft_freq(n, t)
tibble(
  frequency = freq,
  power = fft_powers(fc)
) %>%
  ggplot(aes(frequency, power)) +
  geom_col() +
  theme_bw()
```


```{r prediction}
preds <- tibble(time = seq(0, t, by = 0.01)) %>%
  mutate(temperature = fft_reconstruct(f = fc, freq = freq, time = time))
g +
  geom_line(data = preds)
```
